SELECT ticker,
date,
total_assets,
total_debt,
invested_capital,
working_capital,
stockholders_equity,
retained_earnings,
long_term_debt,
current_assets,
current_liabilities,
current_debt,
payables_and_accrued_expenses,
total_liabilities_net_minority_interest,
accounts_payable,
accounts_receivable,
investments_and_advances,
net_ppe,
inventory,
receivables,
cash_and_cash_equivalents,
cash_cash_equivalents_and_short_term_investments,
goodwill,
common_stock,
share_issued
FROM balance_sheet_quarter